version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/todo

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300

    - location: scripts/start_server.sh
      timeout: 300
