install:
  runtime-versions:
    python: 3.10
    java: corretto17
  commands:
    - echo "Cleaning up old files..."
    - rm -rf sonar-scanner-5.0.1.3006-linux || true
    - rm -rf /home/ec2-user/todo/sonar-scanner-5.0.1.3006-linux || true
    - echo "Installing dependencies..."
    - pip install -r requirements.txt
    - pip install pylint pylint-django
    - echo "Downloading SonarScanner..."
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
    - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
    - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin
    - export JAVA_HOME=/usr/lib/jvm/java-17
    - export PATH=$JAVA_HOME/bin:$PATH
