version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
      java: corretto17
    commands:
      - echo "Cleaning up old files..."
      - rm -rf sonar-scanner-5.0.1.3006-linux || true
      - echo "Installing pip3 and project dependencies..."
      - yum install -y python3 python3-pip
      - python3 -m pip install --upgrade pip
      - python3 -m pip install -r requirements.txt
      - python3 -m pip install pylint pylint-django
      - echo "Downloading and Installing SonarScanner..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - mkdir -p /opt/sonar-scanner
      - mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
      - export PATH=$PATH:/opt/sonar-scanner/bin
      - export JAVA_HOME=/usr/lib/jvm/java-17
      - export PATH=$JAVA_HOME/bin:$PATH

  build:
    commands:
      - echo "Running static code analysis"
      - python3 -m pylint tasks todo_project manage.py
      - java -version
      - sonar-scanner -Dsonar.projectKey=Vaju744_todo-app \
                      -Dsonar.host.url=https://sonarcloud.io \
                      -Dsonar.token=dd84e7ac7b01444324701fd7f484e986601a892f \
                      -Dsonar.exclusions="**/env/**,**/__pycache__/**" || true

  post_build:
    commands:
      - echo "Static code analysis completed successfully"
      - echo "Build phase complete"

artifacts:
  files:
    - '**/*'
  name: build-artifact.zip
  discard-paths: no
