version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python -m unittest discover  # Run tests
artifacts:
  files:
    - '**/*'