branch-defaults:
  main:
    environment: todo-x23325666
  old-version:
    environment: x23325666-to-do-app
environment-defaults:
  todo-x23325666:
    branch: null
    repository: null
  x23325666-to-do-app:
    branch: null
    repository: null
global:
  application_name: todo-eb
  default_ec2_keyname: todoapp
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
